debug: true
language: zh-CN
site:
    brand: 服务器
    cookiename: server-dash
    theme: default
    dashboardtheme: default
    customcode: ""
    customcodedashboard: ""
    viewpassword: ""
oauth2:
    type: github
    admin: 
    admingroups: ""
    clientid: 
    clientsecret: 
    endpoint: ""
    oidcdisplayname: OIDC
    oidcissuer: ""
    oidclogouturl: ""
    oidcregisterurl: ""
    oidcloginclaim: sub
    oidcgroupclaim: groups
    oidcscopes: openid,profile,email
    oidcautocreate: false
    oidcautologin: false
httpport: 5555
grpcport: 6666
grpchost: grpc.xxx.com
proxygrpcport: 443
tls: true
enableplainipinnotification: true
disableswitchtemplateinfrontend: false
enableipchangenotification: true
ipchangenotificationtag: default
cover: 0
ignoredipnotification: "26"
location: Asia/Shanghai
ignoredipnotificationserverids:
    26: true
maxtcppingvalue: 450
avgpingcount: 2
dnsservers: ""
databasetype: badger
databaselocation: data/sqlite.db
geoipdb: data/ipinfo_lite.mmdb